### ISSUE TITLE
Having Issue when Keyboard is Presented 

### ISSUE THREAD

**Issue by visherandro** [Morfly/MultiState-BottomSheet#2]
When a TextField is put in a Composable and if i try to adjust the height of the sheet based on Keyboard visibility it works fine but after entering any text the sheet changes the height automatically and hides few views. 

Kindly guide me on how to properly implement keyboard handling using this library.

**Comment by Morfly** [comment]
Hi @visherandro 
Please check this [stackoverflow thread](https://stackoverflow.com/a/76069567). It could provide a hint on how to solve the keyboard issue
